CREATE DATABASE HOTEL
USE HOTEL


CREATE TABLE ROOMTYPES(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(50) NOT NULL,
PRICE MONEY
)

INSERT INTO ROOMTYPES VALUES('SUITE',100)
INSERT INTO ROOMTYPES VALUES('PRESIDENTIAL',200)
INSERT INTO ROOMTYPES VALUES('STUDIO',300)
SELECT*FROM ROOMTYPES

CREATE TABLE ROOMS(
ID INT PRIMARY KEY IDENTITY,
[NAME] NVARCHAR(50) NOT NULL,
ROOMTYPESID INT REFERENCES ROOMTYPES(ID)
)
INSERT INTO ROOMS VALUES('11A',1)
INSERT INTO ROOMS VALUES('11B',2)
INSERT INTO ROOMS VALUES('11C',3)
SELECT*FROM ROOMS

CREATE TABLE CUSTOMERS(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(50) NOT NULL,
PASSWORDID NVARCHAR(50) NOT NULL UNIQUE,
ROOMSID INT REFERENCES ROOMS(ID)
)
INSERT INTO CUSTOMERS VALUES('Emilya Agheyeva','6P304S8',1)
INSERT INTO CUSTOMERS VALUES('Gulchin Taghizade','7P203H7',2)
INSERT INTO CUSTOMERS VALUES('Lusi Pusi','9P201H7',3)
SELECT*FROM CUSTOMERS

CREATE TABLE PAYMENTS(
ID INT PRIMARY KEY IDENTITY,
CUSTOMERSID INT REFERENCES CUSTOMERS(ID),
ROOMTYPESID INT REFERENCES ROOMTYPES(ID)
)

INSERT INTO PAYMENTS VALUES(1,1)
INSERT INTO PAYMENTS VALUES(2,2)
INSERT INTO PAYMENTS VALUES(3,3)
SELECT*FROM PAYMENTS

CREATE TABLE RESERVATIONS(
ID INT PRIMARY KEY IDENTITY,
CUSTOMERSID INT REFERENCES CUSTOMERS(ID),
ROOMSID INT REFERENCES ROOMS(ID),
RESERVATIONDATE DATE
)

INSERT INTO RESERVATIONS VALUES(1,1,'2022/04/22')
INSERT INTO RESERVATIONS VALUES(2,2,'2021/07/21')
INSERT INTO RESERVATIONS VALUES(3,3,'2020/04/20')


CREATE VIEW GETCUSTOMERS
AS
SELECT C.NAME,C.ROOMSID,C.PASSWORDID,ROOMS.[NAME] 'ROOMNO'  FROM CUSTOMERS C
JOIN  RESERVATIONS RS
ON 
RS.CUSTOMERSID=C.ID 
JOIN ROOMS 
ON
ROOMS.ID=C.ROOMSID

SELECT*FROM GETCUSTOMERS

CREATE VIEW GETCUSTOMERANDROOMTYPES
AS
SELECT C.NAME,R.[NAME] 'ROOMTYPESNAME' FROM PAYMENTS
JOIN CUSTOMERS C
ON 
PAYMENTS.CUSTOMERSID=C.ID
JOIN ROOMTYPES R
ON 
PAYMENTS.ROOMTYPESID=R.ID

SELECT*FROM GETCUSTOMERANDROOMTYPES


CREATE PROCEDURE SHOWCUSTOMERANDROOMS @ID INT
AS
SELECT C.NAME,C.PASSWORDID,R.NAME FROM CUSTOMERS C 
JOIN RESERVATIONS RS
ON
RS.CUSTOMERSID=C.ID
JOIN ROOMS R
ON
R.ID=C.ROOMSID
WHERE @ID=C.ID

EXEC SHOWCUSTOMERANDROOMS 1


CREATE FUNCTION GETTFUNCTION(@GETROOMS VARCHAR(50))
RETURNS INT
AS
BEGIN
DECLARE @NUM INT
SELECT @NUM=COUNT(NAME) FROM ROOMS WHERE NAME=@GETROOMS
RETURN @NUM
END

SELECT DBO.GETTFUNCTION('11C')



CREATE FUNCTION ROOMTYPEPRICE (@GETPRICE INT)
RETURNS TABLE
AS
RETURN(SELECT*FROM ROOMTYPES WHERE ROOMTYPES.PRICE> @GETPRICE)

SELECT NAME FROM DBO.ROOMTYPEPRICE(100)
